/**
 * RBAC Constants — ملف الثوابت الخاصة بالتحكم بالوصول بناءً على الدور
 * defines ROLE_PERMISSIONS and ROLE_META used throughout the application
 */

// Role permissions mapping — خريطة تصريح كل دور
// Each role now includes profession scoping: professions: UUID[]
// These professions are the ones this role can inspect/evaluate/manage
// via the profession_applicability bridge table
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  ministry_admin: [
    '*all',
    'entities:read',
    'entities:write',
    'workers:read',
    'workers:write',
    'violations:read',
    'violations:write',
    'inspections:read',
    'inspections:write',
    'compliance_alerts:read',
    'compliance_alerts:write',
    'risk_assessments:read',
    'risk_assessments:write',
    'compliance_matrices:read',
    'compliance_matrices:write',
    'maturity_assessments:read',
    'maturity_assessments:write',
    'labor_disputes:read',
    'labor_disputes:write',
    'expatriate_licenses:read',
    'expatriate_licenses:write',
    'evaluation_certificates:read',
    'evaluation_certificates:write',
    'services:read',
    'services:write',
    'isic4_classifications:read',
    'isic4_classifications:write',
    'worker_reduction_requests:read',
    'worker_reduction_requests:write',
    'board_members:read',
    'board_members:write',
    'elections:read',
    'elections:write',
    'notifications:read',
    'notifications:write',
    'profiles:read',
    'profiles:write',
    'organizational_entities:read',
    'organizational_entities:write',
    'commercial_establishments:read',
    'commercial_establishments:write',
    'enterprise_occupation_links:read',
    'enterprise_occupation_links:write',
    'entity_relationships:read',
    'entity_relationships:write',
    'documents:read',
    'documents:write',
    'members:read',
    'members:write',
    'activities:read',
    'activities:write',
    'licenses:read',
    'licenses:write',
    'fee_payments:read',
    'fee_payments:write',
    'dashboard:read',
    'dashboard:write',
    'reports:read',
    'reports:write',
    'users:read',
    'users:write',
    'settings:read',
    'settings:write',
  ],
  supervisory_director: [
    '*all',
    'entities:read',
    'entities:write',
    'workers:read',
    'workers:write',
    'violations:read',
    'violations:write',
    'inspections:read',
    'inspections:write',
    'compliance_alerts:read',
    'compliance_alerts:write',
    'risk_assessments:read',
    'risk_assessments:write',
    'compliance_matrices:read',
    'compliance_matrices:write',
    'maturity_assessments:read',
    'maturity_assessments:write',
    'labor_disputes:read',
    'labor_disputes:write',
    'expatriate_licenses:read',
    'expatriate_licenses:write',
    'evaluation_certificates:read',
    'evaluation_certificates:write',
    'services:read',
    'services:write',
    'isic4_classifications:read',
    'isic4_classifications:write',
    'worker_reduction_requests:read',
    'worker_reduction_requests:write',
    'board_members:read',
    'board_members:write',
    'elections:read',
    'elections:write',
    'notifications:read',
    'notifications:write',
    'profiles:read',
    'profiles:write',
    'organizational_entities:read',
    'organizational_entities:write',
    'commercial_establishments:read',
    'commercial_establishments:write',
    'enterprise_occupation_links:read',
    'enterprise_occupation_links:write',
    'entity_relationships:read',
    'entity_relationships:write',
    'documents:read',
    'documents:write',
    'members:read',
    'members:write',
    'activities:read',
    'activities:write',
    'licenses:read',
    'licenses:write',
    'fee_payments:read',
    'fee_payments:write',
    'dashboard:read',
    'dashboard:write',
    'reports:read',
    'reports:write',
    'users:read',
    'users:write',
  ],
  // --- RBAC WITH PROFESSION SCOPING BELOW ---

  labor_inspector: [
    'entities:read',
    'entities:write',
    'violations:read',
    'violations:write',
    'inspections:read',
    'inspections:write',
    'compliance_alerts:read',
    'risk_assessments:read',
    'dashboard:read',
    // Profession scoping: can only inspect enterprises where their assigned professions apply
    // This will be enforced at the API/service level using profession_applicability
  ],
  compliance_officer: [
    'entities:read',
    'compliance_alerts:read',
    'compliance_alerts:write',
    'risk_assessments:read',
    'risk_assessments:write',
    'dashboard:read',
    'reports:read',
    // Can evaluate certificates for professions within their scope
  ],
  legal_counsel: [
    'entities:read',
    'compliance_alerts:read',
    'risk_assessments:read',
    'compliance_matrices:read',
    'dashboard:read',
    'reports:read',
  ],
  registry_officer: [
    'organizational_entities:read',
    'organizational_entities:write',
    'commercial_establishments:read',
    'commercial_establishments:write',
    'dashboard:read',
    // Can register new profession-applicability links
    // (link professions to enterprises/activities)
  ],
  reports_viewer: [
    'dashboard:read',
    'reports:read',
    'entities:read',
    // Read-only access to all reports and evaluation results
  ],
  union_president: [
    'entities:read',
    'members:read',
    'dashboard:read',
    'services:read',
    // Can view evaluations for union's assigned professions
  ],
  hr_officer: [
    'members:read',
    'members:write',
    'dashboard:read',
    // HR-related functions - member management
  ],
  financial_officer: [
    'fee_payments:read',
    'fee_payments:write',
    'dashboard:read',
    // Financial operations - fee payments
  ],
};

// Role metadata — بيانات تعريف كل دور (العرض واللون)
// Updated to include profession scope information
export const ROLE_META: Record<string, { label: string; color: string; description: string }> = {
  ministry_admin: {
    label: 'إدارة وزارة',
    color: 'bg-blue-600',
    description: 'Full access to all system functions and professions',
  },
  supervisory_director: {
    label: 'مدير إشرافي',
    color: 'bg-blue-700',
    description: 'Senior administrative access across all entities',
  },
  labor_inspector: {
    label: 'تفتيش 노동',
    color: 'bg-green-600',
    description: 'Conduct inspections within assigned profession scope',
  },
  compliance_officer: {
    label: 'فني امتثال',
    color: 'bg-yellow-600',
    description: 'Ensure compliance within profession scope',
  },
  legal_counsel: {
    label: 'Conseiller Juridique',
    color: 'bg-orange-600',
    description: 'Legal compliance and advice',
  },
  registry_officer: {
    label: 'مسجل',
    color: 'bg-purple-600',
    description: 'Register professions and enterprises applicability',
  },
  reports_viewer: {
    label: 'مشاهد تقارير',
    color: 'bg-gray-600',
    description: 'View reports and evaluation results',
  },
  union_president: {
    label: 'رئيس اتحاد',
    color: 'bg-orange-500',
    description: 'Union leadership - view evaluations for union professions',
  },
  hr_officer: {
    label: 'موظف ressources humaines',
    color: 'bg-teal-600',
    description: 'Human resources member management',
  },
  financial_officer: {
    label: 'موظف مالي',
    color: 'bg-red-600',
    description: 'Financial operations and fee management',
  },
};