import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';

export default tseslint.config([
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    ignores: [
      'dist',
      'node_modules',
      'supabase/functions/**',
      '*.config.js',
      '*.config.mjs',
      'public',
      'coverage',
      'vitest.config.ts',
      'vite.config.ts',
      '**/*.sql',
    ],
  },
  // Server-side .js files — Node.js globals + relaxed rules
  {
    files: ['server/**/*.js'],
    languageOptions: {
      globals: {
        process: 'readonly',
        Buffer: 'readonly',
        console: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        crypto: 'readonly',
        fetch: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'writable',
      },
    },
    rules: {
      'no-console': 'off',
      'no-unused-vars': 'off',
      'no-undef': 'off',
      'no-useless-escape': 'off',
    },
  },
  // Scripts — Node.js globals (all extensions used in scripts/)
  {
    files: ['scripts/**/*.mjs', 'scripts/**/*.cjs', 'scripts/**/*.js', 'scripts/**/*.ts'],
    languageOptions: {
      globals: {
        process: 'readonly',
        Buffer: 'readonly',
        console: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        AbortSignal: 'readonly',
        AbortController: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'writable',
        fs: 'readonly',
        path: 'readonly',
        os: 'readonly',
        crypto: 'readonly',
        https: 'readonly',
        http: 'readonly',
        url: 'readonly',
        net: 'readonly',
        tls: 'readonly',
        dns: 'readonly',
        dgram: 'readonly',
        child_process: 'readonly',
        cluster: 'readonly',
        readline: 'readonly',
        repl: 'readonly',
        stream: 'readonly',
        util: 'readonly',
        v8: 'readonly',
        vm: 'readonly',
        zlib: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      'no-undef': 'off',
      'no-empty': 'off',
      'no-useless-escape': 'off',
      'no-unused-expressions': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      'react': reactPlugin,
      'react-hooks': reactHooksPlugin,
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { 'argsIgnorePattern': '^_', 'varsIgnorePattern': '^_', 'caughtErrorsIgnorePattern': '^_', 'destructuredArrayIgnorePattern': '^_' }],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'no-console': ['warn', { 'allow': ['error', 'warn'] }],
      '@typescript-eslint/no-floating-promises': 'off',
    },
    settings: {
      'react': {
        'version': 'detect',
      },
    },
  },
]);