import pg from 'pg';
import { readFileSync } from 'fs';
const env = readFileSync('G:\\App25\\unionministry1\\.env','utf8').split('\n');
env.forEach(l => { const t=l.trim(); if(!t||t.startsWith('#'))return; const i=t.indexOf('='); if(i===-1)return; const k=t.slice(0,i).trim(); const v=t.slice(i+1).trim().replace(/^['"]|['"]$/g,''); if(!process.env[k])process.env[k]=v; });
const pool = new pg.Pool({connectionString: process.env.DATABASE_URL, ssl:{rejectUnauthorized:false}, max:1});
const r = await pool.query("SELECT column_name FROM information_schema.columns WHERE table_name='organizational_entities' AND (column_name LIKE '%id' OR column_name='entity_id') LIMIT 10");
console.log(r.rows.map(x=>x.column_name));
const pk = await pool.query("SELECT a.attname FROM pg_index i JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey) WHERE i.indrelid = 'organizational_entities'::regclass AND i.indisprimary");
console.log('PK:', pk.rows.map(x=>x.attname));
await pool.end();
