/**
 * laborRecordsConfig.ts — التكوين المركزي لسجلات قطاع شؤون العمل
 * وفق "المتطلبات الإضافية للنظام" (برنامج قطاع شؤون العمل)
 * واجهات config-driven مولّدة من هذا الملف — أي سجل جديد يُضاف هنا فقط.
 */
import type { LucideIcon } from 'lucide-react';
import {
  Building, ClipboardCheck, Users, Shield, Briefcase, HeartPulse,
  BadgeCheck, UserCog, FileBadge, FileCheck2, Map,
} from 'lucide-react';

export type FieldType = 'text' | 'number' | 'date' | 'select' | 'textarea' | 'boolean' | 'email' | 'phone';

export interface FieldDef {
  name: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: string[];
  placeholder?: string;
  colSpan?: 1 | 2;
  help?: string;
}

export interface RecordConfig {
  /** المعرّف داخل المصنع: directorates, ministry-offices, ... */
  resource: string;
  /** اسم الجدول في SQL */
  table: string;
  title: string;
  subtitle: string;
  icon: LucideIcon;
  /** أعمدة الجدول المعروضة (في الواجهة) */
  columns: Array<{ key: string; label: string; width?: string; type?: 'text' | 'badge' | 'number' | 'date' | 'boolean' }>;
  /** حقول نموذج الإضافة/التعديل */
  fields: FieldDef[];
  /** فلاتر سريعة أعلى الجدول (قيم enum في السجل) */
  filters: Array<{ key: string; label: string; options: string[] }>;
  /** حقول البحث */
  searchKeys: string[];
  /** مفتاح العرض الأساسي (يظهر في العنوان الجانبي / القوائم المنسدلة) */
  displayField: string;
  /** هل يظهر في لوحة إحصاءات المكون */
  showInStats?: boolean;
}

export const LABOR_RECORDS: RecordConfig[] = [
  {
    resource: 'directorates',
    table: 'directorates',
    title: 'سجل المديريات',
    subtitle: 'المستوى الثاني في التسلسل الإداري: محافظة / مديرية / عزلة — يربط دخول النظام بالمحافظة والمديرية',
    icon: Map,
    columns: [
      { key: 'name_ar', label: 'اسم المديرية' },
      { key: 'governorate', label: 'المحافظة', type: 'badge' },
      { key: 'code', label: 'الرمز' },
      { key: 'created_at', label: 'تاريخ الإنشاء', type: 'date' },
    ],
    fields: [
      { name: 'name_ar', label: 'اسم المديرية', type: 'text', required: true, colSpan: 1 },
      { name: 'governorate', label: 'المحافظة', type: 'text', required: true, colSpan: 1 },
      { name: 'code', label: 'الرمز', type: 'text', placeholder: 'مثال: ADN-01', colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [],
    searchKeys: ['name_ar', 'code', 'governorate'],
    displayField: 'name_ar',
  },
  {
    resource: 'ministry-offices',
    table: 'ministry_offices',
    title: 'سجل مكاتب الوزارة',
    subtitle: 'مكاتب الوزارة بثلاثة مستويات (وزارة / مكتب محافظة / مكتب مديرية) مع الاختصاص والموقع',
    icon: Building,
    columns: [
      { key: 'office_name', label: 'اسم المكتب' },
      { key: 'office_level', label: 'المستوى', type: 'badge' },
      { key: 'governorate', label: 'المحافظة' },
      { key: 'manager_name', label: 'المدير' },
      { key: 'phone', label: 'الهاتف' },
      { key: 'status', label: 'الحالة', type: 'badge' },
    ],
    fields: [
      { name: 'office_name', label: 'اسم المكتب', type: 'text', required: true, colSpan: 2 },
      { name: 'office_code', label: 'كود المكتب', type: 'text', colSpan: 1 },
      { name: 'office_level', label: 'المستوى', type: 'select', options: ['وزارة', 'مكتب محافظة', 'مكتب مديرية'], colSpan: 1 },
      { name: 'governorate', label: 'المحافظة', type: 'text', colSpan: 1 },
      { name: 'directorate_id', label: 'معرّف المديرية', type: 'text', placeholder: 'UUID المديرية (اختياري)', colSpan: 1 },
      { name: 'jurisdiction', label: 'الاختصاص', type: 'text', placeholder: 'نطاق العمل القانوني', colSpan: 2 },
      { name: 'manager_name', label: 'اسم المدير', type: 'text', colSpan: 1 },
      { name: 'manager_phone', label: 'هاتف المدير', type: 'phone', colSpan: 1 },
      { name: 'address', label: 'العنوان', type: 'text', colSpan: 2 },
      { name: 'phone', label: 'الهاتف', type: 'phone', colSpan: 1 },
      { name: 'email', label: 'البريد الإلكتروني', type: 'email', colSpan: 1 },
      { name: 'employees_count', label: 'عدد الموظفين', type: 'number', colSpan: 1 },
      { name: 'status', label: 'الحالة', type: 'select', options: ['نشط', 'متوقف', 'مؤجل'], colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [
      { key: 'office_level', label: 'المستوى', options: ['وزارة', 'مكتب محافظة', 'مكتب مديرية'] },
      { key: 'status', label: 'الحالة', options: ['نشط', 'متوقف', 'مؤجل'] },
    ],
    searchKeys: ['office_name', 'office_code', 'manager_name', 'jurisdiction'],
    displayField: 'office_name',
  },
  {
    resource: 'inspectors',
    table: 'inspectors',
    title: 'سجل المفتشين',
    subtitle: 'مفتشو الوزارة والمكاتب — يرتبطون بمكاتب الوزارة والتفتيش الميداني',
    icon: ClipboardCheck,
    columns: [
      { key: 'full_name', label: 'الاسم' },
      { key: 'inspector_code', label: 'الرمز' },
      { key: 'specialization', label: 'الاختصاص' },
      { key: 'employment_source', label: 'جهة التوظيف', type: 'badge' },
      { key: 'inspector_level', label: 'المستوى', type: 'badge' },
      { key: 'status', label: 'الحالة', type: 'badge' },
    ],
    fields: [
      { name: 'full_name', label: 'الاسم الكامل', type: 'text', required: true, colSpan: 2 },
      { name: 'inspector_code', label: 'رمز المفتش', type: 'text', colSpan: 1 },
      { name: 'national_id', label: 'الرقم الوطني', type: 'text', colSpan: 1 },
      { name: 'gender', label: 'الجنس', type: 'select', options: ['ذكر', 'أنثى'], colSpan: 1 },
      { name: 'job_title', label: 'المسمى الوظيفي', type: 'text', colSpan: 1 },
      { name: 'specialization', label: 'الاختصاص', type: 'text', placeholder: 'سلامة مهنية / شؤون عمل / ...', colSpan: 1 },
      { name: 'inspector_level', label: 'المستوى', type: 'select', options: ['مفتش متدرب', 'مبتدئ', 'متوسط', 'مفتش', 'متخصص', 'متقدم'], colSpan: 1 },
      { name: 'employment_source', label: 'جهة التوظيف', type: 'select', options: ['من الوزارة', 'من المكتب'], colSpan: 1 },
      { name: 'office_id', label: 'معرّف المكتب', type: 'text', placeholder: 'UUID المكتب (اختياري)', colSpan: 1 },
      { name: 'phone', label: 'الهاتف', type: 'phone', colSpan: 1 },
      { name: 'email', label: 'البريد الإلكتروني', type: 'email', colSpan: 1 },
      { name: 'appointment_date', label: 'تاريخ التعيين', type: 'date', colSpan: 1 },
      { name: 'is_osh_certified', label: 'حاصل على شهادة سلامة مهنية', type: 'boolean', colSpan: 1 },
      { name: 'last_evaluation_score', label: 'آخر تقييم', type: 'number', colSpan: 1 },
      { name: 'status', label: 'الحالة', type: 'select', options: ['نشط', 'متوقف', 'إجازة', 'منتهي'], colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [
      { key: 'status', label: 'الحالة', options: ['نشط', 'متوقف', 'إجازة', 'منتهي'] },
      { key: 'inspector_level', label: 'المستوى', options: ['مفتش متدرب', 'مبتدئ', 'متوسط', 'مفتش', 'متخصص', 'متقدم'] },
      { key: 'employment_source', label: 'جهة التوظيف', options: ['من الوزارة', 'من المكتب'] },
    ],
    searchKeys: ['full_name', 'inspector_code', 'national_id', 'specialization'],
    displayField: 'full_name',
  },
  {
    resource: 'ministry-employees',
    table: 'ministry_employees',
    title: 'سجل الموظفين',
    subtitle: 'موظفو الوزارة والمكاتب — بمرجعية بطاقة الوصف الوظيفي لبرنامج التدريب والتقييم',
    icon: UserCog,
    columns: [
      { key: 'full_name', label: 'الاسم' },
      { key: 'job_title', label: 'المسمى' },
      { key: 'department', label: 'الإدارة' },
      { key: 'employment_type', label: 'نوع التعيين', type: 'badge' },
      { key: 'status', label: 'الحالة', type: 'badge' },
    ],
    fields: [
      { name: 'full_name', label: 'الاسم الكامل', type: 'text', required: true, colSpan: 2 },
      { name: 'employee_code', label: 'كود الموظف', type: 'text', colSpan: 1 },
      { name: 'national_id', label: 'الرقم الوطني', type: 'text', colSpan: 1 },
      { name: 'gender', label: 'الجنس', type: 'select', options: ['ذكر', 'أنثى'], colSpan: 1 },
      { name: 'job_title', label: 'المسمى الوظيفي', type: 'text', colSpan: 1 },
      { name: 'department', label: 'الإدارة / القطاع', type: 'text', colSpan: 1 },
      { name: 'office_id', label: 'معرّف المكتب', type: 'text', placeholder: 'UUID المكتب (اختياري)', colSpan: 1 },
      { name: 'employment_type', label: 'نوع التعيين', type: 'select', options: ['دائم', 'تعاقدي', 'موقت', 'متدرب'], colSpan: 1 },
      { name: 'job_description_ref', label: 'مرجع بطاقة الوصف الوظيفي', type: 'text', colSpan: 2 },
      { name: 'qualification', label: 'المؤهل', type: 'text', colSpan: 1 },
      { name: 'hire_date', label: 'تاريخ التعيين', type: 'date', colSpan: 1 },
      { name: 'phone', label: 'الهاتف', type: 'phone', colSpan: 1 },
      { name: 'email', label: 'البريد الإلكتروني', type: 'email', colSpan: 1 },
      { name: 'status', label: 'الحالة', type: 'select', options: ['نشط', 'متوقف', 'إعارة', 'متقاعد'], colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [
      { key: 'status', label: 'الحالة', options: ['نشط', 'متوقف', 'إعارة', 'متقاعد'] },
      { key: 'employment_type', label: 'نوع التعيين', options: ['دائم', 'تعاقدي', 'موقت', 'متدرب'] },
    ],
    searchKeys: ['full_name', 'employee_code', 'national_id', 'job_title', 'department'],
    displayField: 'full_name',
  },
  {
    resource: 'inspection-criteria',
    table: 'inspection_criteria',
    title: 'سجل معايير التفتيش',
    subtitle: 'معايير التفتيش الدوري والموجه — مرتبطة بالقطاع ونوع المنشأة والنشاط الاقتصادي',
    icon: Shield,
    columns: [
      { key: 'title_ar', label: 'المعيار' },
      { key: 'sector', label: 'القطاع', type: 'badge' },
      { key: 'inspection_kind', label: 'نوع التفتيش', type: 'badge' },
      { key: 'applies_to', label: 'الانطباق' },
      { key: 'frequency_months', label: 'الدورية (شهر)', type: 'number' },
      { key: 'is_mandatory', label: 'إلزامي', type: 'boolean' },
      { key: 'status', label: 'الحالة', type: 'badge' },
    ],
    fields: [
      { name: 'title_ar', label: 'عنوان المعيار', type: 'text', required: true, colSpan: 2 },
      { name: 'criteria_code', label: 'رمز المعيار', type: 'text', colSpan: 1 },
      { name: 'legal_reference', label: 'المرجع القانوني (المادة)', type: 'text', colSpan: 1 },
      { name: 'sector', label: 'القطاع', type: 'select', options: ['عام', 'حكومي', 'تجاري', 'صناعي', 'سياحي', 'مصرفي', 'تعليمي', 'صحي', 'تعدين', 'مختلط', 'خاص', 'خدمي'], colSpan: 1 },
      { name: 'establishment_type', label: 'نوع المنشأة', type: 'text', placeholder: 'شركة / مؤسسة / محل / مركز / مكتب / ورشة...', colSpan: 1 },
      { name: 'activity_isic4', label: 'رمز النشاط ISIC-4', type: 'text', colSpan: 1 },
      { name: 'inspection_kind', label: 'نوع التفتيش', type: 'select', options: ['دوري', 'حسب الطلب', 'متخصص', 'استثنائي', 'إعادة تفتيش'], colSpan: 1 },
      { name: 'applies_to', label: 'ينطبق على', type: 'select', options: ['جميع المنشآت', 'حسب القطاع', 'حسب النوع', 'حسب النشاط', 'حسب الحجم'], colSpan: 1 },
      { name: 'frequency_months', label: 'الدورية بالأشهر', type: 'number', colSpan: 1 },
      { name: 'weight', label: 'الوزن', type: 'number', colSpan: 1 },
      { name: 'is_mandatory', label: 'معيار إلزامي', type: 'boolean', colSpan: 1 },
      { name: 'description', label: 'الوصف', type: 'textarea', colSpan: 2 },
      { name: 'status', label: 'الحالة', type: 'select', options: ['ساري', 'موقوف'], colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [
      { key: 'sector', label: 'القطاع', options: ['عام', 'حكومي', 'تجاري', 'صناعي', 'سياحي', 'مصرفي', 'تعليمي', 'صحي', 'تعدين', 'مختلط', 'خاص', 'خدمي'] },
      { key: 'inspection_kind', label: 'نوع التفتيش', options: ['دوري', 'حسب الطلب', 'متخصص', 'استثنائي', 'إعادة تفتيش'] },
      { key: 'status', label: 'الحالة', options: ['ساري', 'موقوف'] },
    ],
    searchKeys: ['title_ar', 'criteria_code', 'legal_reference'],
    displayField: 'title_ar',
  },
  {
    resource: 'work-injuries',
    table: 'work_injuries',
    title: 'سجل الإصابات العملية والأمراض المهنية',
    subtitle: 'إصابات العمل والأمراض المهنية والوفيات — مشترك بين العامل والمنشأة وفق قانون العمل',
    icon: HeartPulse,
    columns: [
      { key: 'injury_number', label: 'رقم الحالة' },
      { key: 'worker_name', label: 'العامل' },
      { key: 'enterprise_name', label: 'المنشأة' },
      { key: 'case_type', label: 'النوع', type: 'badge' },
      { key: 'severity', label: 'الخطورة', type: 'badge' },
      { key: 'injury_date', label: 'التاريخ', type: 'date' },
      { key: 'status', label: 'الحالة', type: 'badge' },
    ],
    fields: [
      { name: 'worker_name', label: 'اسم العامل', type: 'text', required: true, colSpan: 2 },
      { name: 'worker_national_id', label: 'الرقم الوطني', type: 'text', colSpan: 1 },
      { name: 'injury_number', label: 'رقم الحالة', type: 'text', colSpan: 1 },
      { name: 'case_type', label: 'نوع الحالة', type: 'select', options: ['إصابة عمل', 'مرض مهني', 'وفاة عمل', 'إعاقة عمل'], colSpan: 1 },
      { name: 'enterprise_name', label: 'اسم المنشأة', type: 'text', colSpan: 1 },
      { name: 'commercial_register', label: 'السجل التجاري', type: 'text', colSpan: 1 },
      { name: 'governorate', label: 'المحافظة', type: 'text', colSpan: 1 },
      { name: 'injury_date', label: 'تاريخ الإصابة', type: 'date', required: true, colSpan: 1 },
      { name: 'report_date', label: 'تاريخ البلاغ', type: 'date', colSpan: 1 },
      { name: 'severity', label: 'درجة الخطورة', type: 'select', options: ['بسيطة', 'متوسطة', 'خطيرة', 'وفاة'], colSpan: 1 },
      { name: 'body_part', label: 'العضو المصاب', type: 'text', colSpan: 1 },
      { name: 'cause_description', label: 'وصف السبب', type: 'textarea', colSpan: 2 },
      { name: 'location', label: 'الموقع', type: 'text', colSpan: 1 },
      { name: 'lost_work_days', label: 'أيام العمل الضائعة', type: 'number', colSpan: 1 },
      { name: 'medical_facility', label: 'المنشأة الطبية', type: 'text', colSpan: 1 },
      { name: 'medical_status', label: 'الحالة الطبية', type: 'text', colSpan: 1 },
      { name: 'insurance_claimed', label: 'تم المطالبة بالتأمين', type: 'boolean', colSpan: 1 },
      { name: 'claim_number', label: 'رقم المطالبة', type: 'text', colSpan: 1 },
      { name: 'compensation_amount', label: 'مبلغ التعويض', type: 'number', colSpan: 1 },
      { name: 'committee_decision', label: 'قرار اللجنة', type: 'textarea', colSpan: 2 },
      { name: 'status', label: 'الحالة', type: 'select', options: ['مبلغة', 'قيد التحقيق', 'قيد المعالجة', 'مغلقة', 'معوَّضة'], colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [
      { key: 'status', label: 'الحالة', options: ['مبلغة', 'قيد التحقيق', 'قيد المعالجة', 'مغلقة', 'معوَّضة'] },
      { key: 'severity', label: 'الخطورة', options: ['بسيطة', 'متوسطة', 'خطيرة', 'وفاة'] },
      { key: 'case_type', label: 'النوع', options: ['إصابة عمل', 'مرض مهني', 'وفاة عمل', 'إعاقة عمل'] },
    ],
    searchKeys: ['injury_number', 'worker_name', 'worker_national_id', 'enterprise_name'],
    displayField: 'worker_name',
  },
  {
    resource: 'insurance-records',
    table: 'insurance_records',
    title: 'سجل التأمينات',
    subtitle: 'وثائق التأمينات بأنواعها — إصابات العمل، تقاعد، صحي، شامل، بطالة',
    icon: BadgeCheck,
    columns: [
      { key: 'policy_number', label: 'رقم الوثيقة' },
      { key: 'insured_name', label: 'المؤمَّن' },
      { key: 'insurance_type', label: 'النوع', type: 'badge' },
      { key: 'provider_name', label: 'المزوّد' },
      { key: 'coverage_start', label: 'البداية', type: 'date' },
      { key: 'coverage_end', label: 'النهاية', type: 'date' },
      { key: 'status', label: 'الحالة', type: 'badge' },
    ],
    fields: [
      { name: 'insured_name', label: 'اسم المؤمَّن عليه', type: 'text', required: true, colSpan: 2 },
      { name: 'policy_number', label: 'رقم الوثيقة', type: 'text', colSpan: 1 },
      { name: 'insured_national_id', label: 'الرقم الوطني', type: 'text', colSpan: 1 },
      { name: 'insurance_type', label: 'نوع التأمين', type: 'select', options: ['تأمين إصابات عمل', 'تأمين تقاعد', 'تأمين صحي', 'تأمين شامل', 'تأمين بطالة'], colSpan: 1 },
      { name: 'enterprise_name', label: 'اسم المنشأة', type: 'text', colSpan: 1 },
      { name: 'provider_name', label: 'شركة التأمين', type: 'text', colSpan: 1 },
      { name: 'coverage_start', label: 'تاريخ بدء التغطية', type: 'date', colSpan: 1 },
      { name: 'coverage_end', label: 'تاريخ انتهاء التغطية', type: 'date', colSpan: 1 },
      { name: 'premium_amount', label: 'قيمة الأقساط', type: 'number', colSpan: 1 },
      { name: 'coverage_amount', label: 'مبلغ التغطية', type: 'number', colSpan: 1 },
      { name: 'beneficiaries_count', label: 'عدد المستفيدين', type: 'number', colSpan: 1 },
      { name: 'linked_injury_id', label: 'معرّف إصابة مرتبطة', type: 'text', placeholder: 'UUID إصابة (اختياري)', colSpan: 1 },
      { name: 'status', label: 'الحالة', type: 'select', options: ['نشط', 'منتهي', 'معلق', 'ملغي'], colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [
      { key: 'insurance_type', label: 'النوع', options: ['تأمين إصابات عمل', 'تأمين تقاعد', 'تأمين صحي', 'تأمين شامل', 'تأمين بطالة'] },
      { key: 'status', label: 'الحالة', options: ['نشط', 'منتهي', 'معلق', 'ملغي'] },
    ],
    searchKeys: ['policy_number', 'insured_name', 'enterprise_name', 'provider_name'],
    displayField: 'insured_name',
  },
  {
    resource: 'irregular-workers',
    table: 'irregular_workers',
    title: 'سجل العمالة غير المنتظمة',
    subtitle: 'عمال غير منتظمين — باعة متجولون، نقل، ورش منزلية — مع مسارات التوطين والتأهيل',
    icon: Users,
    columns: [
      { key: 'full_name', label: 'الاسم' },
      { key: 'activity_type', label: 'نشاط العمل', type: 'badge' },
      { key: 'governorate', label: 'المحافظة' },
      { key: 'has_insurance', label: 'مؤمَّن', type: 'boolean' },
      { key: 'registered_via', label: 'طريقة التسجيل' },
      { key: 'status', label: 'الحالة', type: 'badge' },
    ],
    fields: [
      { name: 'full_name', label: 'الاسم الكامل', type: 'text', required: true, colSpan: 2 },
      { name: 'registration_number', label: 'رقم القيد', type: 'text', colSpan: 1 },
      { name: 'national_id', label: 'الرقم الوطني', type: 'text', colSpan: 1 },
      { name: 'gender', label: 'الجنس', type: 'select', options: ['ذكر', 'أنثى'], colSpan: 1 },
      { name: 'birth_date', label: 'تاريخ الميلاد', type: 'date', colSpan: 1 },
      { name: 'nationality', label: 'الجنسية', type: 'text', colSpan: 1 },
      { name: 'governorate', label: 'المحافظة', type: 'text', colSpan: 1 },
      { name: 'directorate_id', label: 'معرّف المديرية', type: 'text', placeholder: 'UUID المديرية (اختياري)', colSpan: 1 },
      { name: 'district', label: 'العزلة / الحي', type: 'text', colSpan: 1 },
      { name: 'phone', label: 'الهاتف', type: 'phone', colSpan: 1 },
      { name: 'activity_type', label: 'نوع النشاط', type: 'text', placeholder: 'بيع متجول / نقل / ورشة منزلية / زراعة موسمية...', colSpan: 1 },
      { name: 'workplace_description', label: 'وصف مكان العمل', type: 'text', colSpan: 2 },
      { name: 'daily_income', label: 'الدخل اليومي', type: 'number', colSpan: 1 },
      { name: 'monthly_income', label: 'الدخل الشهري', type: 'number', colSpan: 1 },
      { name: 'has_insurance', label: 'مشمول بالتأمين', type: 'boolean', colSpan: 1 },
      { name: 'has_fitness_certificate', label: 'لديه شهادة لياقة صحية', type: 'boolean', colSpan: 1 },
      { name: 'registered_via', label: 'طريقة التسجيل', type: 'select', options: ['مكتب تسجيل', 'المنصة الإلكترونية', 'حملة ميدانية'], colSpan: 1 },
      { name: 'registered_at', label: 'تاريخ التسجيل', type: 'date', colSpan: 1 },
      { name: 'regularization_path', label: 'مسار التوطين / التأهيل', type: 'text', colSpan: 2 },
      { name: 'status', label: 'الحالة', type: 'select', options: ['مسجل', 'قيد التحقق', 'تم توطينه', 'غير نشط'], colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [
      { key: 'status', label: 'الحالة', options: ['مسجل', 'قيد التحقق', 'تم توطينه', 'غير نشط'] },
    ],
    searchKeys: ['full_name', 'registration_number', 'national_id', 'activity_type'],
    displayField: 'full_name',
  },
  {
    resource: 'health-fitness-certificates',
    table: 'health_fitness_certificates',
    title: 'سجل شهادات اللياقة الصحية',
    subtitle: 'شهادات اللياقة الصحية للعمال — فحوصات أولية وقيود طبية مع تنبيهات الانتهاء',
    icon: FileBadge,
    columns: [
      { key: 'certificate_number', label: 'رقم الشهادة' },
      { key: 'worker_name', label: 'العامل' },
      { key: 'enterprise_name', label: 'المنشأة' },
      { key: 'fitness_result', label: 'النتيجة', type: 'badge' },
      { key: 'exam_date', label: 'تاريخ الفحص', type: 'date' },
      { key: 'expiry_date', label: 'تاريخ الانتهاء', type: 'date' },
      { key: 'status', label: 'الحالة', type: 'badge' },
    ],
    fields: [
      { name: 'worker_name', label: 'اسم العامل', type: 'text', required: true, colSpan: 2 },
      { name: 'certificate_number', label: 'رقم الشهادة', type: 'text', colSpan: 1 },
      { name: 'worker_national_id', label: 'الرقم الوطني', type: 'text', colSpan: 1 },
      { name: 'enterprise_name', label: 'اسم المنشأة', type: 'text', colSpan: 1 },
      { name: 'occupation', label: 'المهنة', type: 'text', colSpan: 1 },
      { name: 'exam_date', label: 'تاريخ الفحص', type: 'date', colSpan: 1 },
      { name: 'exam_center', label: 'مركز الفحص', type: 'text', colSpan: 1 },
      { name: 'doctor_name', label: 'اسم الطبيب', type: 'text', colSpan: 1 },
      { name: 'fitness_result', label: 'النتيجة', type: 'select', options: ['لياق كامل', 'لياق مشروط', 'غير لائق', 'يحتاج فحوصات إضافية'], colSpan: 1 },
      { name: 'expiry_date', label: 'تاريخ الانتهاء', type: 'date', colSpan: 1 },
      { name: 'initial_screening', label: 'فحص أولي', type: 'boolean', colSpan: 1 },
      { name: 'restrictions', label: 'قيود العمل الطبية', type: 'textarea', colSpan: 2 },
      { name: 'status', label: 'الحالة', type: 'select', options: ['سارية', 'منتهية', 'ملغاة'], colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [
      { key: 'status', label: 'الحالة', options: ['سارية', 'منتهية', 'ملغاة'] },
      { key: 'fitness_result', label: 'النتيجة', options: ['لياق كامل', 'لياق مشروط', 'غير لائق', 'يحتاج فحوصات إضافية'] },
    ],
    searchKeys: ['certificate_number', 'worker_name', 'worker_national_id', 'enterprise_name'],
    displayField: 'worker_name',
  },
  {
    resource: 'experience-certificates',
    table: 'experience_certificates',
    title: 'سجل شهادات الخبرة',
    subtitle: 'شهادات الخبرة والتعميد — مرتبطة بدليل تصنيف المهن الوطني (ISCO)',
    icon: FileCheck2,
    columns: [
      { key: 'certificate_number', label: 'رقم الشهادة' },
      { key: 'worker_name', label: 'العامل' },
      { key: 'occupation', label: 'المهنة' },
      { key: 'experience_years', label: 'سنوات الخبرة', type: 'number' },
      { key: 'experience_level', label: 'المستوى', type: 'badge' },
      { key: 'is_verified', label: 'موثقة', type: 'boolean' },
      { key: 'status', label: 'الحالة', type: 'badge' },
    ],
    fields: [
      { name: 'worker_name', label: 'اسم العامل', type: 'text', required: true, colSpan: 2 },
      { name: 'certificate_number', label: 'رقم الشهادة', type: 'text', colSpan: 1 },
      { name: 'worker_national_id', label: 'الرقم الوطني', type: 'text', colSpan: 1 },
      { name: 'occupation', label: 'المهنة', type: 'text', colSpan: 1 },
      { name: 'occupation_code', label: 'رمز المهنة (ISCO)', type: 'text', colSpan: 1 },
      { name: 'enterprise_name', label: 'المنشأة / الجهة', type: 'text', colSpan: 1 },
      { name: 'experience_years', label: 'سنوات الخبرة', type: 'number', colSpan: 1 },
      { name: 'experience_level', label: 'المستوى', type: 'select', options: ['مبتدئ', 'متوسط', 'مهرة', 'خبير', 'متقدم'], colSpan: 1 },
      { name: 'issued_by', label: 'جهة الإصدار', type: 'text', colSpan: 1 },
      { name: 'issue_date', label: 'تاريخ الإصدار', type: 'date', colSpan: 1 },
      { name: 'verified_by', label: 'جهة التوثيق', type: 'text', colSpan: 1 },
      { name: 'verification_date', label: 'تاريخ التوثيق', type: 'date', colSpan: 1 },
      { name: 'is_verified', label: 'موثقة', type: 'boolean', colSpan: 1 },
      { name: 'status', label: 'الحالة', type: 'select', options: ['صادرة', 'موثقة', 'ملغاة'], colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [
      { key: 'status', label: 'الحالة', options: ['صادرة', 'موثقة', 'ملغاة'] },
      { key: 'experience_level', label: 'المستوى', options: ['مبتدئ', 'متوسط', 'مهرة', 'خبير', 'متقدم'] },
    ],
    searchKeys: ['certificate_number', 'worker_name', 'worker_national_id', 'occupation', 'enterprise_name'],
    displayField: 'worker_name',
  },
  {
    resource: 'work-procedures',
    table: 'worker_procedures',
    title: 'سجل إجراءات العمل',
    subtitle: 'إجراءات التعيين والإنهاء والنقل والتسوية — وفق بطاقة الوصف الوظيفي',
    icon: Briefcase,
    columns: [
      { key: 'procedure_code', label: 'رمز الإجراء' },
      { key: 'procedure_name', label: 'اسم الإجراء' },
      { key: 'procedure_type', label: 'النوع', type: 'badge' },
      { key: 'worker_name', label: 'العامل' },
      { key: 'enterprise_name', label: 'المنشأة' },
      { key: 'start_date', label: 'البداية', type: 'date' },
      { key: 'status', label: 'الحالة', type: 'badge' },
    ],
    fields: [
      { name: 'procedure_name', label: 'اسم الإجراء', type: 'text', required: true, colSpan: 2 },
      { name: 'procedure_code', label: 'رمز الإجراء', type: 'text', colSpan: 1 },
      { name: 'procedure_type', label: 'نوع الإجراء', type: 'select', options: ['تعيين', 'إنهاء عقد', 'نقل خدمة', 'استقالة', 'إعارة', 'تسوية'], colSpan: 1 },
      { name: 'worker_name', label: 'اسم العامل', type: 'text', required: true, colSpan: 1 },
      { name: 'worker_national_id', label: 'الرقم الوطني', type: 'text', colSpan: 1 },
      { name: 'enterprise_name', label: 'اسم المنشأة', type: 'text', colSpan: 1 },
      { name: 'occupation', label: 'المهنة', type: 'text', colSpan: 1 },
      { name: 'start_date', label: 'تاريخ البداية', type: 'date', colSpan: 1 },
      { name: 'end_date', label: 'تاريخ النهاية', type: 'date', colSpan: 1 },
      { name: 'reference_number', label: 'الرقم المرجعي', type: 'text', colSpan: 1 },
      { name: 'approved_by', label: 'الجهة المعتمدة', type: 'text', colSpan: 1 },
      { name: 'approval_date', label: 'تاريخ الاعتماد', type: 'date', colSpan: 1 },
      { name: 'legal_basis', label: 'الأساس القانوني (المادة)', type: 'text', colSpan: 2 },
      { name: 'description', label: 'الوصف', type: 'textarea', colSpan: 2 },
      { name: 'status', label: 'الحالة', type: 'select', options: ['مسودة', 'قيد المراجعة', 'معتمد', 'مرفوض', 'ملغي'], colSpan: 1 },
      { name: 'notes', label: 'ملاحظات', type: 'textarea', colSpan: 2 },
    ],
    filters: [
      { key: 'status', label: 'الحالة', options: ['مسودة', 'قيد المراجعة', 'معتمد', 'مرفوض', 'ملغي'] },
      { key: 'procedure_type', label: 'النوع', options: ['تعيين', 'إنهاء عقد', 'نقل خدمة', 'استقالة', 'إعارة', 'تسوية'] },
    ],
    searchKeys: ['procedure_name', 'procedure_code', 'worker_name', 'worker_national_id', 'enterprise_name'],
    displayField: 'procedure_name',
  },
];

/** قائمة المحافظات اليمنية للتعبئة السريعة */
export const YEMEN_GOVERNORATES = [
  'أمانة العاصمة', 'عدن', 'تعز', 'الحديدة', 'إب', 'ذمار', 'المحويت', 'حجة',
  'صعدة', 'عمران', 'صنعاء', 'البيضاء', 'مأرب', 'شبوة', 'أبين', 'لحج',
  'الضالع', 'ريمه', 'الجوف', 'حضرموت', 'المهرة', 'سقطرى',
];

/** خريطة ألوان الحالات العامة */
export const BADGE_COLORS: Record<string, string> = {
  'نشط': 'bg-green-100 text-green-700',
  'ساري': 'bg-green-100 text-green-700',
  'سارية': 'bg-green-100 text-green-700',
  'صادرة': 'bg-green-100 text-green-700',
  'موثقة': 'bg-blue-100 text-blue-700',
  'مبلغة': 'bg-yellow-100 text-yellow-700',
  'قيد التحقيق': 'bg-orange-100 text-orange-700',
  'قيد المعالجة': 'bg-orange-100 text-orange-700',
  'قيد التحقق': 'bg-yellow-100 text-yellow-700',
  'تم توطينه': 'bg-green-100 text-green-700',
  'لياق كامل': 'bg-green-100 text-green-700',
  'لياق مشروط': 'bg-yellow-100 text-yellow-700',
  'غير لائق': 'bg-red-100 text-red-700',
  'يحتاج فحوصات إضافية': 'bg-orange-100 text-orange-700',
  'مغلقة': 'bg-gray-100 text-gray-700',
  'معوَّضة': 'bg-emerald-100 text-emerald-700',
  'منتهي': 'bg-gray-100 text-gray-700',
  'منتهية': 'bg-gray-100 text-gray-700',
  'معلق': 'bg-yellow-100 text-yellow-700',
  'ملغي': 'bg-red-100 text-red-700',
  'ملغاة': 'bg-red-100 text-red-700',
  'متوقف': 'bg-gray-100 text-gray-700',
  'مؤجل': 'bg-yellow-100 text-yellow-700',
  'إجازة': 'bg-blue-100 text-blue-700',
  'متقاعد': 'bg-purple-100 text-purple-700',
  'إعارة': 'bg-blue-100 text-blue-700',
  'موقوف': 'bg-red-100 text-red-700',
  'مسجل': 'bg-blue-100 text-blue-700',
  'غير نشط': 'bg-gray-100 text-gray-700',
  'وزارة': 'bg-purple-100 text-purple-700',
  'مكتب محافظة': 'bg-blue-100 text-blue-700',
  'مكتب مديرية': 'bg-cyan-100 text-cyan-700',
  'من الوزارة': 'bg-purple-100 text-purple-700',
  'من المكتب': 'bg-blue-100 text-blue-700',
  'إصابة عمل': 'bg-red-100 text-red-700',
  'مرض مهني': 'bg-orange-100 text-orange-700',
  'وفاة عمل': 'bg-red-100 text-red-700',
  'إعاقة عمل': 'bg-yellow-100 text-yellow-700',
  'بسيطة': 'bg-green-100 text-green-700',
  'متوسطة': 'bg-yellow-100 text-yellow-700',
  'خطيرة': 'bg-red-100 text-red-700',
  'وفاة': 'bg-gray-100 text-gray-700',
  'تأمين إصابات عمل': 'bg-red-100 text-red-700',
  'تأمين تقاعد': 'bg-blue-100 text-blue-700',
  'تأمين صحي': 'bg-green-100 text-green-700',
  'تأمين شامل': 'bg-purple-100 text-purple-700',
  'تأمين بطالة': 'bg-yellow-100 text-yellow-700',
  'دائم': 'bg-green-100 text-green-700',
  'تعاقدي': 'bg-blue-100 text-blue-700',
  'موقت': 'bg-yellow-100 text-yellow-700',
  'متدرب': 'bg-purple-100 text-purple-700',
  'دوري': 'bg-blue-100 text-blue-700',
  'حسب الطلب': 'bg-yellow-100 text-yellow-700',
  'متخصص': 'bg-purple-100 text-purple-700',
  'استثنائي': 'bg-red-100 text-red-700',
  'إعادة تفتيش': 'bg-orange-100 text-orange-700',
  'مبتدئ': 'bg-yellow-100 text-yellow-700',
  'متوسط': 'bg-blue-100 text-blue-700',
  'مهرة': 'bg-green-100 text-green-700',
  'خبير': 'bg-purple-100 text-purple-700',
  'متقدم': 'bg-primary/10 text-primary',
  'مفتش': 'bg-blue-100 text-blue-700',
  'مفتش متدرب': 'bg-yellow-100 text-yellow-700',
  'خاص': 'bg-blue-100 text-blue-700',
  'عام': 'bg-gray-100 text-gray-700',
  'حكومي': 'bg-purple-100 text-purple-700',
  'تجاري': 'bg-blue-100 text-blue-700',
  'صناعي': 'bg-orange-100 text-orange-700',
  'سياحي': 'bg-teal-100 text-teal-700',
  'مصرفي': 'bg-emerald-100 text-emerald-700',
  'تعليمي': 'bg-indigo-100 text-indigo-700',
  'صحي': 'bg-red-100 text-red-700',
  'تعدين': 'bg-yellow-100 text-yellow-700',
  'مختلط': 'bg-purple-100 text-purple-700',
  'خدمي': 'bg-cyan-100 text-cyan-700',
};

export function getBadgeColor(value: string | undefined | null): string {
  if (!value) return 'bg-gray-100 text-gray-700';
  return BADGE_COLORS[value] || 'bg-gray-100 text-gray-700';
}

export function findRecordConfig(resource: string): RecordConfig | undefined {
  return LABOR_RECORDS.find(r => r.resource === resource);
}